class_name BakeAssetIds
extends RefCounted

## 把 manifest 的 4 个 section 转成 AssetIds 常量类。
## output_path 是单一 .gd 文件路径（不是目录）。
static func bake(manifest: Dictionary, output_path: String) -> Dictionary:
    var errors: Array[String] = []

    var lines: Array[String] = []
    lines.append("# AUTO-GENERATED by tools/godot_bake/bake_asset_ids.gd. DO NOT EDIT.")
    lines.append("# Last bake: %s" % Time.get_datetime_string_from_system())
    lines.append("")
    lines.append("class_name AssetIds")
    lines.append("extends RefCounted")
    lines.append("")

    var sprites: Dictionary = manifest.get("sprites", {})
    lines.append("class Char:")
    if sprites.is_empty():
        lines.append("    pass")
    else:
        for entry_id in sprites.keys():
            lines.append("    const %s := \"%s\"" % [String(entry_id).to_upper(), entry_id])
    lines.append("")

    var portraits: Dictionary = manifest.get("portraits", {})
    lines.append("class Portrait:")
    if portraits.is_empty():
        lines.append("    pass")
    else:
        for entry_id in portraits.keys():
            lines.append("    class %s:" % _camel(entry_id))
            var exprs: Dictionary = portraits[entry_id].get("expressions", {})
            if exprs.is_empty():
                lines.append("        pass")
            else:
                for expr_name in exprs.keys():
                    lines.append("        const %s := \"%s\"" % [String(expr_name).to_upper(), expr_name])
    lines.append("")

    var vfx: Dictionary = manifest.get("vfx", {})
    lines.append("class Vfx:")
    if vfx.is_empty():
        lines.append("    pass")
    else:
        for entry_id in vfx.keys():
            lines.append("    const %s := \"%s\"" % [String(entry_id).to_upper(), entry_id])
    lines.append("")

    var atlas_section: Dictionary = manifest.get("atlas", {})
    lines.append("class Item:")
    if atlas_section.is_empty():
        lines.append("    pass")
    else:
        for entry_id in atlas_section.keys():
            lines.append("    class %s:" % _camel(entry_id))
            var items: Dictionary = atlas_section[entry_id].get("items", {})
            if items.is_empty():
                lines.append("        pass")
            else:
                for item_name in items.keys():
                    lines.append("        const %s := \"%s\"" % [String(item_name).to_upper(), item_name])
    lines.append("")

    var dir := output_path.get_base_dir()
    DirAccess.make_dir_recursive_absolute(dir)
    var f := FileAccess.open(output_path, FileAccess.WRITE)
    if f == null:
        errors.append("[ERR] asset_ids: cannot open %s" % output_path)
        return { "ok": 0, "skipped": 1, "errors": errors }
    f.store_string("\n".join(lines))
    f.close()

    print("[OK] asset_ids -> %s" % output_path)
    return { "ok": 1, "skipped": 0, "errors": errors }

static func _camel(snake: String) -> String:
    var out := ""
    for part in snake.split("_"):
        if part.length() > 0:
            out += part.substr(0, 1).to_upper() + part.substr(1)
    return out
