# AUTO-GENERATED by tools/godot_bake/bake_asset_ids.gd. DO NOT EDIT.
# Last bake: 2026-05-29T16:05:09

class_name AssetIds
extends RefCounted

class Sprites:
    const YUANSHENG := "yuansheng"

class Portraits:
    pass

class Vfx:
    pass

class Atlas:
    pass
