# AUTO-GENERATED by tools/godot_bake/bake_asset_ids.gd. DO NOT EDIT.
# Last bake: 2026-05-29T17:32:18

class_name AssetIds
extends RefCounted

class Char:
	const YUANSHENG := "yuansheng"

class Portrait:
	pass

class Vfx:
	pass

class Item:
	pass
